application: ermakovaca-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /scripts
  static_dir: static/scripts

- url: /images
  static_dir: static/images

- url: /(.*\.(html|htm))
  static_files: static/\1
  upload: static/(.*\.(html|htm))

- url: /(.*\.css)
  static_files: static/\1
  upload: static/(.*\.css)

- url: /
  script: index.app

- url: /contact.do
  script: contact.app


